typography_spectrum: 0.59904
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.3125
  lightness: 0.1875
  saturation: 0.75
  rhythmicContrast: 0.25
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.70319
analytics:
  google: null
  facebook: null
  twitter: null
name: michalbayerl
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Michal Bayerl
description: Kdo si hraje nezlobí
purpose: []
